### ISSUE TITLE
Error message on export from Inkscape?

### ISSUE THREAD

**Issue by ghost** [pettarin/ink2fxl#1]
Hi,

Thank you for making this, although I haven't gotten far enough to be able to try it yet. Can you please help me with my error code and the solution?

I put the scr files in the extensions folder for Inkscape. I get this message when exporting. I also changed  the Inkscape directory in the options.py, but still no luck:
__inkscape_path = "D:\Program Files (x86)\Inkscape\inkscape.exe"

I get this message when exporting and there is no output created because of it.

Traceback (most recent call last):

  File "ink2fxl.py", line 77, in <module>

```
effect.affect()
```

  File "D:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect

```
self.effect()
```

  File "ink2fxl.py", line 71, in effect

```
converter.parse()
```

  File "D:\Program Files (x86)\Inkscape\share\extensions\svgexporter.py", line 46, in parse

```
parsed_svg_root = parser.parse(self.__svg_file_path)
```

  File "D:\Program Files (x86)\Inkscape\share\extensions\svgparser.py", line 33, in parse

```
self.__parser.parse(data)
```

  File "D:\Program Files (x86)\Inkscape\python\Lib\xml\sax\expatreader.py", line 107, in parse

```
xmlreader.IncrementalParser.parse(self, source)
```

  File "D:\Program Files (x86)\Inkscape\python\Lib\xml\sax\xmlreader.py", line 123, in parse

```
self.feed(buffer)
```

  File "D:\Program Files (x86)\Inkscape\python\Lib\xml\sax\expatreader.py", line 207, in feed

```
self._parser.Parse(data, isFinal)
```

  File "D:\Program Files (x86)\Inkscape\python\Lib\xml\sax\expatreader.py", line 338, in start_element_ns

```
AttributesNSImpl(newattrs, qnames))
```

  File "D:\Program Files (x86)\Inkscape\share\extensions\svgparser.py", line 85, in startElementNS

```
e = element(attrs)
```

  File "D:\Program Files (x86)\Inkscape\share\extensions\svgelements.py", line 329, in **init**

```
self.x = SVGLength(attrs.get((None, "x")))
```

  File "D:\Program Files (x86)\Inkscape\share\extensions\svgelements.py", line 453, in **init**

```
raise
```

TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

**Comment by pettarin** [comment]
Hi, I fixed the "syntactic" problem in v0.0.2. (Those "raise" were copied from the code I inherited from previous projects.)

However, I guess that after downloading the new *py files, you will still get a (different) error, because you are running it over an SVG file not generated by Inkscape --- as it looks like some element does not have the "x" attribute while the code expects it (since Inkscape outputs it): do you confirm my guess? Unfortunately, this is a limitation of the current code, which targets Inkscape-generated SVG. Time permitting, I will try to extend it to handle generic SVG files.
